site_name: MotorXP-AFM Scripting API manual
site_url: https://motorxp.com/
site_description: Documentation.
site_author: MotorXP Team

theme:
  name: material
  icon:
    alternate: octicons/globe-24
  logo: logo.png
  color_mode: auto
  highlightjs: true
  copyright: "© 2025 MotorXP" 
  palette:
    - scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: octicons/sun-24
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  language: ru
  features:
    #- navigation.expand
    #- navigation.tabs
    - content.code.copy
    - content.tabs.link
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - toc.follow

plugins:
  # - search
  - mike
  - offline:
      enabled: !ENV [OFFLINE, false]
  - i18n:
      docs_structure: folder
      reconfigure_material: true
      languages:
        - locale: en
          name: English
          build: true
        - locale: ru
          default: true
          name: Русский
          build: true
          site_name: Руководство MotorXP-AFM Scripting API
          nav_translations:
            Global functions: Глобальные функции
            Constants: Константы
            Script static objects: Встроенные объекты
            Object Types: Типы объектов
            Materials: Материалы
            UI Widgets: UI-виджеты
  - git-revision-date-localized:
        type: datetime

extra_css:
  - css/custom.css

extra:
  version:
    provider: mike
  footer_content: >
    © My Documentation. Последнее обновление: {{ git_revision_date_localized }}

use_directory_urls: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - index.md
  - Global functions:
      - globalFunc/index.md
      - include: globalFunc/include.md
      - require: globalFunc/require.md
      - writeFile: globalFunc/writeFile.md
      - readFile: globalFunc/readFile.md

  - Constants:
      - constants/index.md

  - Script static objects:
      - objects/index.md
      - console:
          - objects/console/index.md
          - methods:
              - objects/console/methods/index.md
              - objects/console/methods/log.md
              - objects/console/methods/info.md
              - objects/console/methods/warn.md
              - objects/console/methods/error.md
              - objects/console/methods/clear.md
              - objects/console/methods/dir.md

      - motor:
          - objects/motor/index.md
          - properties:
              - objects/motor/props/index.md
              - machineType: objects/motor/props/machineType.md
              - objectName: objects/motor/props/objectName.md
              - height: objects/motor/props/height.md
              - periodicity: objects/motor/props/periodicity.md
              - periodicityAngleSpan: objects/motor/props/periodicityAngleSpan.md
              - boundaryConditionMode: objects/motor/props/boundaryConditionMode.md
              - boundaryCondition: objects/motor/props/boundaryCondition.md
              - simDomain: objects/motor/props/simDomain.md
              - simRadialOuterDomain: objects/motor/props/simRadialOuterDomain.md
              - stator: objects/motor/props/stator.md
              - rotor: objects/motor/props/rotor.md
              - winding: objects/motor/props/winding.md
              - mesh: objects/motor/props/mesh.md

      - stator:
          - objects/stator/index.md
          - properties:
              - objects/stator/props/index.md
              - objectName: objects/stator/props/objectName.md
              - outerDiameter: objects/stator/props/outerDiameter.md
              - outerRadius: objects/stator/props/outerRadius.md
              - innerDiameter: objects/stator/props/innerDiameter.md
              - innerRadius: objects/stator/props/innerRadius.md
              - numberSlots: objects/stator/props/numberSlots.md
              - slotAngleSpan: objects/stator/props/slotAngleSpan.md
              - typeMiddleItem: objects/stator/props/typeMiddleItem.md
              - ironMaterial: objects/stator/props/ironMaterial.md
              - ironStacking: objects/stator/props/ironStacking.md
              - windingMaterial: objects/stator/props/windingMaterial.md
              - windingTemperature: objects/stator/props/windingTemperature.md
              - script: objects/stator/props/script.md
              - nameScript: objects/stator/props/nameScript.md
              - countItem: objects/stator/props/countItem.md
              - items: objects/stator/props/items.md
              - simDomain: objects/stator/props/simDomain.md
              - simRadialOuterDomain: objects/stator/props/simRadialOuterDomain.md
          - methods:
              - objects/stator/methods/index.md
              - item: objects/stator/methods/item.md
              - isLower: objects/stator/methods/isLower.md
              - isMiddle: objects/stator/methods/isMiddle.md
              - isUpper: objects/stator/methods/isUpper.md
              - itemAngularDisplacement: objects/stator/methods/itemAngularDisplacement.md
              - setItemAngularDisplacement: objects/stator/methods/setItemAngularDisplacement.md

      - statorItem:
          - objects/statorItem/index.md
          - properties:
              - objects/statorItem/props/index.md
              - objectName: objects/statorItem/props/objectName.md
              - id: objects/statorItem/props/id.md
              - height: objects/statorItem/props/height.md
          - methods:
              - objects/stator/statorItem/index.md
              - isUpper: objects/statorItem/methods/isUpper.md
              - isMiddle: objects/statorItem/methods/isMiddle.md
              - isLower: objects/statorItem/methods/isLower.md
              - angularDisplacement: objects/statorItem/methods/angularDisplacement.md
              - setAngularDisplacement: objects/statorItem/methods/setAngularDisplacement.md

      - rotor:
          - objects/rotor/index.md
          - properties:
              - objects/rotor/props/index.md
              - outerDiameter: objects/rotor/props/outerDiameter.md
              - outerRadius: objects/rotor/props/outerRadius.md
              - innerDiameter: objects/rotor/props/innerDiameter.md
              - innerRadius: objects/rotor/props/innerRadius.md
              - numberPolePairs: objects/rotor/props/numberPolePairs.md
              - poleAngleSpan: objects/rotor/props/poleAngleSpan.md
              - poleArrangement: objects/rotor/props/poleArrangement.md
              - typeMiddleItem: objects/rotor/props/typeMiddleItem.md
              - ironStacking: objects/rotor/props/ironStacking.md
              - ironMaterial: objects/rotor/props/ironMaterial.md
              - magnetTemperature: objects/rotor/props/magnetTemperature.md
              - magnetMaterial: objects/rotor/props/magnetMaterial.md
              - conductorTemperature: objects/rotor/props/conductorTemperature.md
              - conductorMaterial: objects/rotor/props/conductorMaterial.md
              - script: objects/rotor/props/script.md
              - nameScript: objects/rotor/props/nameScript.md
              - countItem: objects/rotor/props/countItem.md
              - items: objects/rotor/props/items.md
              - simDomain: objects/rotor/props/simDomain.md
              - simRadialOuterDomain: objects/rotor/props/simRadialOuterDomain.md
          - methods:
              - objects/rotor/methods/index.md
              - item: objects/rotor/methods/item.md
              - isLower: objects/rotor/methods/isLower.md
              - isMiddle: objects/rotor/methods/isMiddle.md
              - isUpper: objects/rotor/methods/isUpper.md
              - itemAngularDisplacement: objects/rotor/methods/itemAngularDisplacement.md
              - setItemAngularDisplacement: objects/rotor/methods/setItemAngularDisplacement.md

      - rotorItem:
          - objects/rotorItem/index.md
      - coil:
          - objects/coil/index.md
      - winding:
          - objects/winding/index.md
      - mesh:
          - objects/mesh/index.md
      - simDomain:
          - objects/simDomain/index.md
      - Geom:
          - objects/geom/index.md
      - Extra 'Math':
          - func/math/index.md

  - Object Types:
      - types/index.md

  - Materials:
      - materials/index.md

  - UI Widgets:
      - widgets/index.md
      - QGridLayout: widgets/index1.md
      - NumberEdit: widgets/index2.md
      - NumberSlotSpinBox: widgets/index3.md
      - StatorTypeComboBox: widgets/index4.md
      - WindingLayersComboBox: widgets/index6.md
      - WindingLayersOrientationComboBox: widgets/index7.md
      - WindingTypeComboBox: widgets/index8.md
      - PoleArrangementComboBox: widgets/index9.md
      - StatorConnectionComboBox: widgets/index10.md
      - RotorConnectionComboBox: widgets/index11.md
