site_name: MotorXP-AFM Scripting API manual
site_url: https://motorxp.com/
site_description: Documentation.
site_author: MotorXP Team
site_dir: ScriptingAPI_manual
copyright: "Copyright &copy; 2025 MotorXP" 

theme:
  name: material
  custom_dir: docs/overrides
  icon:
    alternate: octicons/globe-24
  logo: logo.png
  color_mode: auto
  highlightjs: true
  palette:
    - scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: octicons/sun-24
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  language: ru
  features:
    #- navigation.expand
    #- navigation.tabs
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    #- navigation.footer

plugins:
  #- search
  - mike
  - offline:
      enabled: !ENV [OFFLINE, false]
  - privacy
  - i18n:
      docs_structure: folder
      reconfigure_material: true
      languages:
        - locale: en
          name: English
          build: true
        - locale: ru
          default: true
          name: Русский
          build: true
          site_name: Руководство MotorXP-AFM Scripting API
          nav_translations:
            Global methods: Глобальные функции
            Constants: Константы
            Script static objects: Встроенные объекты
            Object Types: Типы объектов
            Affine transformations: Аффинные преобразования
            Materials: Материалы
            UI Widgets: UI-виджеты

  - git-revision-date-localized:
        type: datetime
  # - with-pdf
  - print-site:
        path_to_pdf: "document.pdf"
        # add_to_navigation: true     
extra_css:
  - css/custom.css

extra:
  version:
    provider: mike
  generator: true
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/motorxp
    - icon: fontawesome/brands/github 
      link: https://github.com/MotorXP

use_directory_urls: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - toc:
      permalink: true

nav:
  - index.md
  - Global methods:
      - globalFuncs/index.md
      - include(): globalFuncs/include.md
      - require(): globalFuncs/require.md
      - writeFile(): globalFuncs/writeFile.md
      - readFile(): globalFuncs/readFile.md

  - Constants:
      - constants/index.md
      - Motor : constants/Motor.md
      - Stator : constants/Stator.md
      - StatorItem : constants/StatorItem.md
      - Rotor : constants/Rotor.md
      - RotorItem : constants/RotorItem.md
      - Winding : constants/Winding.md
      - Coil : constants/Coil.md
      - Magnetization : constants/Magnetization.md
      - PoleArrangement : constants/PoleArrangement.md
      - Qt : constants/Qt.md

  - Script static objects:
      - objects/index.md
      - console:
          - objects/console/index.md
          - methods:
              - objects/console/methods/index.md
              - objects/console/methods/log.md
              - objects/console/methods/info.md
              - objects/console/methods/warn.md
              - objects/console/methods/error.md
              - objects/console/methods/clear.md
              - objects/console/methods/dir.md

      - motor:
          - objects/motor/index.md
          - properties:
              - objects/motor/props/index.md
              - machineType: objects/motor/props/machineType.md
              - objectName: objects/motor/props/objectName.md
              - height: objects/motor/props/height.md
              - periodicity: objects/motor/props/periodicity.md
              - periodicityAngleSpan: objects/motor/props/periodicityAngleSpan.md
              - boundaryConditionMode: objects/motor/props/boundaryConditionMode.md
              - boundaryCondition: objects/motor/props/boundaryCondition.md
              - simDomain: objects/motor/props/simDomain.md
              - simRadialOuterDomain: objects/motor/props/simRadialOuterDomain.md
              - stator: objects/motor/props/stator.md
              - rotor: objects/motor/props/rotor.md
              - winding: objects/motor/props/winding.md
              - mesh: objects/motor/props/mesh.md

      - stator:
          - objects/stator/index.md
          - properties:
              - objects/stator/props/index.md
              - objectName: objects/stator/props/objectName.md
              - outerDiameter: objects/stator/props/outerDiameter.md
              - outerRadius: objects/stator/props/outerRadius.md
              - innerDiameter: objects/stator/props/innerDiameter.md
              - innerRadius: objects/stator/props/innerRadius.md
              - numberSlots: objects/stator/props/numberSlots.md
              - slotAngleSpan: objects/stator/props/slotAngleSpan.md
              - typeMiddleItem: objects/stator/props/typeMiddleItem.md
              - ironMaterial: objects/stator/props/ironMaterial.md
              - ironStacking: objects/stator/props/ironStacking.md
              - windingMaterial: objects/stator/props/windingMaterial.md
              - windingTemperature: objects/stator/props/windingTemperature.md
              - script: objects/stator/props/script.md
              - nameScript: objects/stator/props/nameScript.md
              - countItem: objects/stator/props/countItem.md
              - items: objects/stator/props/items.md
              - simDomain: objects/stator/props/simDomain.md
              - simRadialOuterDomain: objects/stator/props/simRadialOuterDomain.md
          - methods:
              - objects/stator/methods/index.md
              - item: objects/stator/methods/item.md
              - isLower: objects/stator/methods/isLower.md
              - isMiddle: objects/stator/methods/isMiddle.md
              - isUpper: objects/stator/methods/isUpper.md
              - itemAngularDisplacement: objects/stator/methods/itemAngularDisplacement.md
              - setItemAngularDisplacement: objects/stator/methods/setItemAngularDisplacement.md

      - statorItem:
          - objects/statorItem/index.md
          - properties:
              - objects/statorItem/props/index.md
              - objectName: objects/statorItem/props/objectName.md
              - id: objects/statorItem/props/id.md
              - height: objects/statorItem/props/height.md
          - methods:
              - objects/stator/statorItem/index.md
              - isUpper: objects/statorItem/methods/isUpper.md
              - isMiddle: objects/statorItem/methods/isMiddle.md
              - isLower: objects/statorItem/methods/isLower.md
              - angularDisplacement: objects/statorItem/methods/angularDisplacement.md
              - setAngularDisplacement: objects/statorItem/methods/setAngularDisplacement.md

      - rotor:
          - objects/rotor/index.md
          - properties:
              - objects/rotor/props/index.md
              - outerDiameter: objects/rotor/props/outerDiameter.md
              - outerRadius: objects/rotor/props/outerRadius.md
              - innerDiameter: objects/rotor/props/innerDiameter.md
              - innerRadius: objects/rotor/props/innerRadius.md
              - numberPolePairs: objects/rotor/props/numberPolePairs.md
              - poleAngleSpan: objects/rotor/props/poleAngleSpan.md
              - poleArrangement: objects/rotor/props/poleArrangement.md
              - typeMiddleItem: objects/rotor/props/typeMiddleItem.md
              - ironStacking: objects/rotor/props/ironStacking.md
              - ironMaterial: objects/rotor/props/ironMaterial.md
              - magnetTemperature: objects/rotor/props/magnetTemperature.md
              - magnetMaterial: objects/rotor/props/magnetMaterial.md
              - conductorTemperature: objects/rotor/props/conductorTemperature.md
              - conductorMaterial: objects/rotor/props/conductorMaterial.md
              - script: objects/rotor/props/script.md
              - nameScript: objects/rotor/props/nameScript.md
              - countItem: objects/rotor/props/countItem.md
              - items: objects/rotor/props/items.md
              - simDomain: objects/rotor/props/simDomain.md
              - simRadialOuterDomain: objects/rotor/props/simRadialOuterDomain.md
          - methods:
              - objects/rotor/methods/index.md
              - item: objects/rotor/methods/item.md
              - isLower: objects/rotor/methods/isLower.md
              - isMiddle: objects/rotor/methods/isMiddle.md
              - isUpper: objects/rotor/methods/isUpper.md
              - itemAngularDisplacement: objects/rotor/methods/itemAngularDisplacement.md
              - setItemAngularDisplacement: objects/rotor/methods/setItemAngularDisplacement.md

      - rotorItem:
          - objects/rotorItem/index.md
          - properties: 
              - objects/rotorItem/props/index.md
              - objectName: objects/rotorItem/props/objectName.md
              - id: objects/rotorItem/props/id.md
              - height: objects/rotorItem/props/height.md
              - angularDisplacement: objects/rotorItem/props/angularDisplacement.md
          - methods:
            - objects/rotorItem/methods/index.md
            - isUpper: objects/rotorItem/methods/isUpper.md
            - isMiddle: objects/rotorItem/methods/isMiddle.md
            - isLower: objects/rotorItem/methods/isLower.md
            - angularDisplacement: objects/rotorItem/methods/angularDisplacement.md
            - setAngularDisplacement: objects/rotorItem/methods/setAngularDisplacement.md

      - coil:
          - objects/coil/index.md

      - winding:
          - objects/winding/index.md
          - properties: 
            - objects/winding/props/index.md
            - objectName: objects/winding/props/objectName.md
            - circuit: objects/winding/props/circuit.md
            - statorConnection: objects/winding/props/statorConnection.md
            - parallelPaths: objects/winding/props/parallelPaths.md
            - numberTurns: objects/winding/props/numberTurns.md
            - strandsConductor: objects/winding/props/strandsConductor.md
            - numberOuterSegments: objects/winding/props/numberOuterSegments.md
            - type: objects/winding/props/type.md
            - numberLayers: objects/winding/props/numberLayers.md
            - layersOrientation: objects/winding/props/layersOrientation.md
            - autoCalcOverhandEndturns: objects/winding/props/autoCalcOverhandEndturns.md
            - radialOverhandOuterEndturn: objects/winding/props/radialOverhandOuterEndturn.md
            - radialOverhandInnerEndturn: objects/winding/props/radialOverhandInnerEndturn.md
            - heightOuterEndturn: objects/winding/props/heightOuterEndturn.md
            - heightInnerEndturn: objects/winding/props/heightInnerEndturn.md
          - methods:
            - objects/winding/methods/index.md
            - isPlanar: objects/winding/methods/isPlanar.md
            - isToroidal: objects/winding/methods/isToroidal.md
            - isSingleLayer: objects/winding/methods/isSingleLayer.md
            - isDoubleLayer: objects/winding/methods/isDoubleLayer.md
            - isOrientationUpperLower: objects/winding/methods/isOrientationUpperLower.md
            - isOrientationLeftRight: objects/winding/methods/isOrientationLeftRight.md
            - checkOverlapEndturns: objects/winding/methods/checkOverlapEndturns.md
            - volumeOverlapEndturns: objects/winding/methods/volumeOverlapEndturns.md
            - distanceBetweenEndturns: objects/winding/methods/distanceBetweenEndturns.md

      - mesh:
          - objects/mesh/index.md
          - properties: 
            - objects/mesh/props/index.md
            - objectName: objects/mesh/props/objectName.md
            - autoSizeBound: objects/mesh/props/autoSizeBound.md
            - sizeBound: objects/mesh/props/sizeBound.md
            - numberSlices: objects/mesh/props/numberSlices.md
            - airgapQuality: objects/mesh/props/airgapQuality.md
            - horizontalSymmetry: objects/mesh/props/horizontalSymmetry.md

      - simDomain:
          - objects/simDomain/index.md
          - properties: 
            - objects/simDomain/props/index.md
            - inner: objects/simDomain/props/inner.md
            - outer: objects/simDomain/props/outer.md
          - methods:
            - objects/simDomain/methods/index.md
            - range: objects/simDomain/methods/range.md

      - Geom:
          - objects/geom/index.md
          - methods:
            - objects/geom/methods/index.md
            - fromPolar: objects/geom/methods/fromPolar.md
            - angle: objects/geom/methods/angle.md
            - angleX: objects/geom/methods/angleX.md
            - angleY: objects/geom/methods/angleY.md
            - angleZ: objects/geom/methods/angleZ.md
            - vector3: objects/geom/methods/vector3.md
            - point3: objects/geom/methods/point3.md
            - segment: objects/geom/methods/segment.md
            - polysegment: objects/geom/methods/polysegment.md
            - bspline: objects/geom/methods/bspline.md
            - arc: objects/geom/methods/arc.md
            - circle: objects/geom/methods/circle.md
            - ellipse: objects/geom/methods/ellipse.md
            - ring: objects/geom/methods/ring.md
            - ngon: objects/geom/methods/ngon.md
            - square: objects/geom/methods/square.md
            - rectangle: objects/geom/methods/rectangle.md
            - polygon: objects/geom/methods/polygon.md
            - infplane: objects/geom/methods/infplane.md
            - box: objects/geom/methods/box.md
            - cylinder: objects/geom/methods/cylinder.md
            - collar: objects/geom/methods/collar.md
            - cone: objects/geom/methods/cone.md
            - sphere: objects/geom/methods/sphere.md
            - torus: objects/geom/methods/torus.md
            - unite: objects/geom/methods/unite.md
            - difference: objects/geom/methods/difference.md
            - intersect: objects/geom/methods/intersect.md
            - fillet: objects/geom/methods/fillet.md
            - chamfer: objects/geom/methods/chamfer.md
            - unify: objects/geom/methods/unify.md
            - length: objects/geom/methods/length.md
            - area: objects/geom/methods/area.md
            - volume: objects/geom/methods/volume.md
            - center: objects/geom/methods/center.md
            - boundingBox: objects/geom/methods/boundingBox.md
            - piece: objects/geom/methods/piece.md

      - Extra 'Math':
          - objects/math/index.md
          - methods:
            - fuzzyIsNull: objects/math/methods/fuzzyIsNull.md
            - fuzzyIsEqual: objects/math/methods/fuzzyIsEqual.md
            - rad: objects/math/methods/rad.md
            - deg: objects/math/methods/deg.md
            - fromPolar: objects/math/methods/fromPolar.md
            - normAngle: objects/math/methods/normAngle.md
            - middleAngle: objects/math/methods/middleAngle.md

  - Object Types:
      - types/index.md
      - Point: types/Point.md
      - Point3: types/Point3.md
      - Vector3: types/Vector3.md

  - Affine transformations:  
      - objects/affine/index.md
      - methods:
        - translate: objects/affine/translate.md

  - Materials:
      - materials/index.md
      - Material: materials/Material.md
      - GeneralMaterial: materials/GeneralMaterial.md
      - IronMaterial: materials/IronMaterial.md
      - WindingMaterial: materials/WindingMaterial.md
      - EndturnMaterial: materials/EndturnMaterial.md
      - MagnetRadialMaterial: materials/MagnetRadialMaterial.md
      - MagnetParallelMaterial: materials/MagnetParallelMaterial.md

  - UI Widgets:
      - widgets/index.md
      - QGridLayout: widgets/QGridLayout.md
      - NumberEdit: widgets/NumberEdit.md
      - NumberSlotSpinBox: widgets/NumberSlotSpinBox.md
      - StatorTypeComboBox: widgets/StatorTypeComboBox.md
      - WindingLayersComboBox: widgets/WindingLayersComboBox.md
      - WindingLayersOrientationComboBox: widgets/WindingLayersOrientationComboBox.md
      - WindingTypeComboBox: widgets/WindingTypeComboBox.md
      - PoleArrangementComboBox: widgets/PoleArrangementComboBox.md
      - StatorConnectionComboBox: widgets/StatorConnectionComboBox.md
      - RotorConnectionComboBox: widgets/RotorConnectionComboBox.md
